#!/bin/sh

set -eu

mount					-t proc		none	/proc

mkdir -p /dev/pts
mount -o nosuid,noexec			-t devpts	none	/dev/pts

mount -o remount,rw,nodev					/

mount -o nosuid,nodev,noexec,mode=1777	-t tmpfs	none	/tmp
mount -o nosuid,nodev,noexec		-t tmpfs	none	/run
mount -o nosuid,nodev			-t tmpfs	none	/var

mkdir -m 1777 /run/lock

# pppd needs these
ln -s /run /var/run
ln -s /run/lock /var/lock

exit 0
