#!/bin/sh

set -eu

. /etc/bratwurst

if [ ! "${HOSTNAME:-}" ]; then
	HOSTNAME=bratwurst
	printf "\nHOSTNAME=%s\n" $HOSTNAME >> /etc/bratwurst
fi

if [ ! "${DOMAIN:-}" ]; then
	DOMAIN=localnet
	printf "\nDOMAIN=%s\n" $DOMAIN >> /etc/bratwurst
fi

hostname $HOSTNAME

grep -q 127.1.0.1 /etc/hosts || sed -i "2i \
127.1.0.1	$HOSTNAME.$DOMAIN	$HOSTNAME" /etc/hosts

exit 0
