#!/bin/sh

set -eu

. /etc/bratwurst

H=${HOSTNAME:-bratwurst}

hostname $H

grep -q ^fd /etc/hosts || sed -i "2i \
$ULA:10::	$H.${DOMAIN:-localnet}	$H
192.168.1.1	$H.${DOMAIN:-localnet}	$H" /etc/hosts

exit 0
