#!/bin/sh

set -eu

[ "${1:-}" != "save" -a -s /etc/random-seed ] && cat /etc/random-seed >/dev/urandom

umask 077
dd if=/dev/urandom of=/etc/random-seed count=1 >/dev/null 2>/dev/null
umask 022

exit 0
