#!/bin/sh

set -eu

. /etc/bratwurst

if [ ! "${ULA:-}" ]; then
	# knowingly using '00' here, and no xxd/sha1sum to do this properly
	ULA="$(printf "%08x\n" $(date +%s) | sed 's/\(....\)\(....\)/fd00:\1:\2/')"
	printf "\nULA=%s\n" $ULA >> /etc/bratwurst
fi

/sbin/ip link set dev lo up
/sbin/ip addr add $ULA:08::/64 dev lo

/sbin/brctl addbr br0
/sbin/brctl setfd br0 0
/sbin/brctl stp br0 off
/sbin/ip addr add $ULA:10::/64 dev br0
/sbin/ip addr add 192.168.1.1/24 dev br0
/sbin/ip link set dev br0 up

# HACK: make sure fakeisp is not added to the bridge
test -d /etc/sv/atmtcp && ip link set dev eth0 up

for IFACE in $(/sbin/ip link | sed -n '/UP/! s/[0-9]*: \([^:]*\).*/\1/ p'); do
	/sbin/ip link set dev $IFACE up
	/sbin/brctl addif br0 $IFACE
done

test -d /etc/sv/atmtcp && ip link set dev eth0 down

exit 0
