#!/bin/sh

set -eu

. /etc/bratwurst

if [ -z "${ULA:-}" ]; then
	I=$(grep -l ^1$ /sys/class/net/*/type | cut -d/ -f5 | sort -nr | head -n1)
	L=$((0x$(cat /sys/class/net/$I/address | cut -d: -f3- | tr -d :) ^ 0x$(dd if=/dev/urandom bs=1 count=4 2>/dev/null | od -X | awk 'NR == 1 { print $2 }')))
	L=${L#-}

	ULA=$(printf "fd%02x:%04x:%04x\n" $((L % 256)) $((L >> 16)) $((L % 65536)))
	printf "\nULA=%s\n" $ULA >> /etc/bratwurst
fi

/sbin/ip link set dev lo up
/sbin/ip addr add $ULA:08::/64 dev lo

/sbin/brctl addbr br0
/sbin/brctl setfd br0 0
/sbin/brctl stp br0 off
/sbin/ip addr add $ULA:10::/64 dev br0
/sbin/ip addr add 192.168.1.1/24 dev br0
/sbin/ip link set dev br0 up

for IFACE in $(ls -1 /sys/class/net); do
	# HACK: make sure fakeisp is not added to the bridge
	[ -d /etc/sv/atmtcp -a "$IFACE" = "eth0" ] && continue || true

	[ ! -d /sys/class/net/$IFACE/bridge ] || continue

	# only ETHER (include/uapi/linux/if_arp.h)
	[ $(cat /sys/class/net/$IFACE/type) -eq 1 ] || continue

	# only DOWN (include/uapi/linux/if.h)
	[ $(($(cat /sys/class/net/$IFACE/flags) & 1)) -eq 0 ] || continue

	/sbin/ip link set dev $IFACE up
	/sbin/brctl addif br0 $IFACE
done

exit 0
