#!/bin/sh

set -eu

. /opt/bratwurst/config

PPP_OPTIONS="	nodetach
		debug
		lock
		lcp-echo-failure 3
		lcp-echo-interval 1
		noauth
		+ipv6
		noipdefault
		defaultroute
		usepeerdns
		user $PPP_USER
		password $PPP_PASS"

if [ "${NETWORK#ppp}" != "$NETWORK" ]; then
	[ -f /proc/net/atm/devices ] || exit 1

	TYPE=$(awk 'NR > 1 { print $2 }' /proc/net/atm/devices)

	# wait for the ATM interface to become available
	[ -n "$TYPE" ] || exit 1

	# wait for carrier, do nothing
	grep -q 1 /sys/class/atm/$TYPE$UPLINK_PORT/carrier || exit 1
fi

case $NETWORK in
pppoa)	/sbin/modprobe pppoatm
	exec /usr/sbin/pppd $PPP_OPTIONS plugin pppoatm.so $UPLINK_PORT.$ATM_VPI.$ATM_VCI
	;;
pppoe)	/sbin/modprobe pppoe
	sv start br2684ctl
	/sbin/ip link set address 00:00:01:00:00:56 dev nas0 up
	exec /usr/sbin/pppd $PPP_OPTIONS plugin rp-pppoe.so nas$UPLINK_PORT
	;;
dhcp)	exec /sbin/udhcpc -f -n -R -t 3 -i $UPLINK_TYPE$UPLINK_PORT
	;;
esac
