#!/bin/sh

set -eu

[ -t 0 -a -t 1 ] || sv once .
touch down

. /opt/bratwurst/config

TYPE=$(awk 'NR > 1 { print $2 }' /proc/net/atm/devices)

# wait for the ATM interface to become available
[ -n "$TYPE" ] || exit 0
# wait for carrier, do nothing (HACK: assume '0')
grep -q 1 /sys/class/atm/${TYPE}0/carrier || exit 0

case $ATM_ENCAP in
llc)		ENCAP=0;;
vcmux)		ENCAP=1;;
esac

exec /usr/sbin/br2684ctl -c $UPLINK_PORT -e $ENCAP -a $UPLINK_PORT.$ATM_VPI.$ATM_VCI
