#!/bin/sh

set -eu

ATM_VPI=0
ATM_VCI=32

PPP_OPTIONS="	nodetach
		debug
		lock
		silent
		lcp-echo-failure 3
		lcp-echo-interval 1
		+ipv6
		ms-dns 172.20.1.0
		172.20.1.0:172.20.1.128"

[ "$(ss -tpn sport = :2812 | sed -n '/^ESTAB.*"atmtcp"/ p')" ] || exit 1

exec /usr/sbin/pppd $PPP_OPTIONS plugin pppoatm.so 0.$ATM_VPI.$ATM_VCI
