#!/bin/sh

set -eu

ATM_VPI=0
ATM_VCI=38

PPP_OPTIONS="	nodetach
		debug
		lock
		silent
		lcp-echo-failure 3
		lcp-echo-interval 1
		+ipv6
		ms-dns 198.51.100.0
		198.51.100.0:198.51.100.1"

exec 2>&1

[ "$(ss -tpn sport = :2812 | sed -n '/^ESTAB.*"atmtcp"/ p')" ] || exit 1

exec /usr/sbin/pppd $PPP_OPTIONS plugin pppoatm.so 0.$ATM_VPI.$ATM_VCI
