#!/bin/sh

set -eu

DEV=ttyS0
BAUD=38400

exec </dev/$DEV >/dev/$DEV 2>&1

# reset
stty sane; stty ispeed $BAUD; stty ospeed $BAUD

printf "%s login: " "$(hostname)"
read -r login

# http://www.busybox.net/FAQ.html#job_control
exec chpst -P sh -c "exec login '$login' </dev/$DEV >/dev/$DEV 2>&1"
