#!/bin/sh

set -eu

set -- $(sed -n 's/.*console=\([^, ]*\),\([0-9]*\).*/\1 \2/ p' /proc/cmdline)

DEV=${1:-ttyS0}
BAUD=${2:-38400}

exec </dev/$DEV >/dev/$DEV 2>&1

# reset
stty sane; stty ispeed $BAUD; stty ospeed $BAUD

printf "%s login: " "$(hostname)"
read -r LOGIN

# http://www.busybox.net/FAQ.html#job_control
exec chpst -P sh -c "exec login '$LOGIN' </dev/$DEV >/dev/$DEV 2>&1"
