#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          bratwurst
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: BRatWuRsT hooks
# Description:
### END INIT INFO

set -eu

runit () {
	systemctl disable wide-dhcpv6-server.service		>/dev/null
	systemctl disable radvd.service				>/dev/null

	for S in $(ls -1 /opt/bratwurst/runit); do
		update-service --add /opt/bratwurst/runit/$S	>/dev/null
	done
}

shared () {
	mkdir /tmp/shared
	mount -t 9p -o version=9p2000.L,trans=virtio shared /tmp/shared
}

passwd -q -d root
runit
shared

exit 0
