#!/bin/sh

set -eu

. /etc/bratwurst

[ "${NETWORK%?}" = "pppo" ] && IFNAME=ppp0 || IFNAME=$UPLINK_TYPE$UPLINK_PORT

if [ "$DOMAIN" != "localnet" ]; then
	OPTIONS="	--no-dhcp-interface=$IFNAME
			--server=/$DOMAIN/ \
			--interface-name=$DOMAIN,lo
			--interface-name=$DOMAIN,$IFNAME
			--auth-zone=$DOMAIN,lo,$IFNAME,br0/6
			--domain=$DOMAIN,192.168.1.0/24,local"
else
	OPTIONS="	--except-interface=$IFNAME"
fi

exec 2>&1
exec /usr/sbin/dnsmasq \
	--keep-in-foreground \
	--expand-hosts \
	--log-facility=- \
	--pid-file \
	--localise-queries \
	--bogus-priv \
	--stop-dns-rebind \
	--rebind-localhost-ok \
	--clear-on-reload \
	--domain-needed \
	--server=/localnet/ \
	--dhcp-range=192.168.1.64,192.168.1.255 \
	--dhcp-range=::,constructor:br0,ra-stateless,ra-names \
	--read-ethers \
	--dhcp-authoritative \
	--dhcp-leasefile=/run/dnsmasq.leases \
	--enable-ra \
	$OPTIONS
