#!/bin/sh

set -eu

. /etc/bratwurst

NETWORK="${NETWORK:-pppoe}"
[ "${NETWORK%?}" = "pppo" ] && IFNAME=ppp0 || IFNAME=eth${UPLINK_PORT:-0}

if [ "${DOMAIN:-localnet}" != "localnet" ]; then
	OPTIONS="	--auth-server=$DOMAIN,$IFNAME
			--server=/$DOMAIN/
			--interface-name=$DOMAIN,lo
			--interface-name=$DOMAIN,$IFNAME
			--auth-zone=$DOMAIN,lo,$IFNAME,br0/6
			--domain=$DOMAIN,192.168.1.0/24,local"
fi

exec 2>&1
exec /usr/sbin/dnsmasq ${OPTIONS:-} \
	--keep-in-foreground \
	--expand-hosts \
	--log-facility=- \
	--pid-file \
	--except-interface=$IFNAME \
	--except-interface=6to4 \
	--local-service \
	--localise-queries \
	--bogus-priv \
	--stop-dns-rebind \
	--rebind-localhost-ok \
	--clear-on-reload \
	--domain-needed \
	--server=/localnet/ \
	--dhcp-range=192.168.1.64,192.168.1.255 \
	--dhcp-range=::,constructor:br0,ra-stateless,ra-names \
	--read-ethers \
	--dhcp-authoritative \
	--dhcp-leasefile=/run/dnsmasq.leases \
	--enable-ra
