#!/bin/sh

set -eu

exec 2>&1

[ -d /etc/dropbear ] || mkdir -p /etc/dropbear

umask 077

for K in rsa dss ecdsa; do
	[ ! -f /etc/dropbear/dropbear_${K}_host_key ] || continue

	echo generating $K key
	/usr/bin/dropbearkey -t $K -f /etc/dropbear/dropbear_${K}_host_key > /dev/null 2>&1
done

umask 022

exec /usr/sbin/dropbear -F -w -s
