#!/bin/sh

set -eu

run-parts /opt/bratwurst/rc.d

mkdir /var/run/sv
find /opt/bratwurst/runit -type d -name supervise | xargs -r rm -rf
find /opt/bratwurst/runit -mindepth 1 -maxdepth 1 -type d \
	| xargs -r -n1 basename \
	| sed 's~.*~/var/run/sv/&\n/opt/bratwurst/runit/&/supervise~' \
	| xargs -r -n2 ln -f -s
find /opt/bratwurst/runit -mindepth 2 -maxdepth 2 -type d -name log \
	| xargs -r -n1 dirname \
	| xargs -r -n1 basename \
	| sed 's~.*~/var/run/sv/&.log\n/opt/bratwurst/runit/&/log/supervise~' \
	| xargs -r -n2 ln -f -s

exec runsvdir -s /sbin/siginit /etc/service
