#!/bin/sh

set -eu

SELF="$(basename "$0")"

case "$SELF" in
reboot)		kill -TERM 1
		exit 0
		;;
halt)		kill -USR1 1
		exit 0
		;;
poweroff)	kill -USR2 1
		exit 0
		;;
esac

shutitdown () {
	echo killing tasks >&2
	ls -1 /var/service | xargs -r sv force-stop || true
	ls -1 /var/service | xargs -r sv exit
	find /var/service -type l | xargs -r rm
	/opt/bratwurst/rc.d/40_urandom stop
	mount -o remount,ro /
}

printf "siginit: received signal $1..." >&2

case "$1" in
1)		# HUP -> restart all runsv processes
		# - handled directly by runsvdir
		echo noop >&2
		;;
15)		# TERM -> reboot
		echo rebooting >&2
		shutitdown
		echo b > /proc/sysrq-trigger
		;;
30|10|16)	# USR1 -> halt
		echo halting >&2
		shutitdown
		echo System Halted >&2
		kill -9 1
		;;
31|12|17)	# USR2 -> poweroff
		echo powering off >&2
		shutitdown
		echo o > /proc/sysrq-trigger
		;;
*)		echo ignoring >&2
esac

exit 0
