#!/bin/sh

set -eu

. /etc/bratwurst

[ -f /run/uplink ] && . /run/uplink || exit 1

if [ "${PREFIX:-}" ]; then
	PD="-P 0"
	PREFIXES="$PREFIX,4294967295,4294967295" \
		/usr/share/dhcpc.script IGNORED informed
fi

exec 2>&1
exec /usr/sbin/odhcp6c -v -e ${PD:-} -s /usr/share/dhcpc.script $IFNAME
