#!/bin/sh

set -eu

mount -a
mount -o remount,rw /

mkdir /var/run
mkdir /var/lock
mkdir /var/tmp

hostname -F /etc/hostname

grep '^[^$#]' /etc/modules | xargs -n1 /sbin/modprobe

test ! -f /opt/bratwurst/rc || . /opt/bratwurst/rc

ifup -a

find /etc/sysctl.d -type f -name '*.conf' | xargs -n1 /sbin/sysctl -q -p

run-parts /etc/nftables

mkdir /var/run/sv
find /etc/sv -type d -name supervise | xargs -r rm -rf
find /etc/sv -mindepth 1 -maxdepth 1 -type d \
	| xargs -r -n1 basename \
	| sed 's~.*~/var/run/sv/&\n/etc/sv/&/supervise~' \
	| xargs -r -n2 ln -f -s
find /etc/sv -mindepth 2 -maxdepth 2 -type d -name log \
	| xargs -r -n1 dirname \
	| xargs -r -n1 basename \
	| sed 's~.*~/var/run/sv/&.log\n/etc/sv/&/log/supervise~' \
	| xargs -r -n2 ln -f -s

exec runsvdir -s /sbin/siginit /etc/service
