#!/bin/sh

set -eu

shutitdown () {
	echo killing tasks >&2
	kill 1
	for I in $(seq 1 3); do
		ls -1 /var/service | xargs sv stop || true
		[ -n "$(ls -1 /var/service | xargs sv status | grep ^run:)" ] || break
	done
	if [ -n "$(ls -1 /var/service | xargs sv status | grep ^run:)" ]; then
		ls -1 /var/service | xargs sv kill || true
	fi
	/bin/umount -a -r || true
	/bin/mount /proc
}

printf siginit: received signal $1... >&2

case "$1" in
1)		# HUP -> restart all runsv processes
		# - handled directly by runsvdir
		echo noop >&2
		exit 0
		;;
15)		# TERM -> reboot
		echo rebooting >&2
		shutitdown
		echo b > /proc/sysrq-trigger
		;;
30|10|16)	# USR1 -> halt
		echo halting >&2
		shutitdown
		kill -9 1
		;;
31|12|17)	# USR2 -> poweroff
		echo powering off >&2
		shutitdown
		echo o > /proc/sysrq-trigger
		;;
*)		echo ignoring >&2
		exit 0
esac

exit 0
