#!/bin/sh

set -eu

. /etc/bratwurst

if [ "$NETWORK" = "dhcp" ]; then
	sv once .
	exit 0
fi

SERVER=172.21.0.0
CLIENT=172.21.0.1

/sbin/ip addr add $CLIENT peer $SERVER dev eth0 2>/dev/null || true
/sbin/ip link set dev eth0 up

# wait for the remote end to become available
timeout -t 3 -s INT nc $SERVER 2812 </dev/null >/dev/null 2>/dev/null || exit 1

# wait for runit to respawn atmtcp on the server side
sleep 3

/sbin/modprobe atmtcp

exec /usr/sbin/atmtcp virtual connect $SERVER
