#!/bin/sh

set -eu

[ -f /run/uplink ] || exit 0

. /run/uplink

[ "${IFNAME:-}" -a "${IPLOCAL:-}" ] || exit 1

CONFIG="$(mktemp)"

cat <<EOF > "$CONFIG"
flush table ip nat;

table ip nat {
	chain prerouting {
		type nat hook prerouting priority 0;
	}

	chain postrouting {
		type nat hook postrouting priority 0;

		ip saddr 192.168.1.0/24 oif $IFNAME snat $IPLOCAL;
	}
}
EOF

/usr/sbin/nft -f "$CONFIG"

rm -f "$CONFIG"

exit 0
