#!/bin/sh

set -eu

(
	flock 9

	echo "IFNAME=$IFNAME" >> /run/uplink
	sed -n -i "/^IFNAME=/!p; /^IFNAME=/h; \${g;p}" /run/uplink

	echo "IPLOCAL=$IPLOCAL" >> /run/uplink
	sed -n -i "/^IPLOCAL=/!p; /^IPLOCAL=/h; \${g;p}" /run/uplink
) 9>>/run/uplink

/etc/nftables/060_nat

exit 0
