#!/bin/sh

set -eu

(
	flock 9

	echo "IFNAME=$IFNAME" >> /run/uplink
	sed -n -i "/^IFNAME=/!p; /^IFNAME=/h; \${g;p}" /run/uplink

	echo "IPLOCAL=$IPLOCAL" >> /run/uplink
	sed -n -i "/^IPLOCAL=/!p; /^IPLOCAL=/h; \${g;p}" /run/uplink
) 9>>/run/uplink

/etc/nftables/060_nat

SIX2FOUR=$(printf "2002:%02x%02x:%02x%02x" $(echo $IPLOCAL | tr . ' '))
/sbin/ip tunnel add 6to4 mode sit remote any local $IPLOCAL
/sbin/ip link set dev 6to4 up
/sbin/ip addr add $SIX2FOUR::/16 dev 6to4
/sbin/ip route add 192.88.99.1 dev $IFNAME
/sbin/ip route add default from 2002::/16 via ::192.88.99.1 dev 6to4
/sbin/ip route add default via ::192.88.99.1 dev 6to4 metric 4096
/sbin/ip addr add $SIX2FOUR:08::/64 dev lo
/sbin/ip addr add $SIX2FOUR:10::/64 dev br0

exit 0
