#!/bin/sh

set -eu

(
	flock 9

	echo "IFNAME=$IFNAME" >> /run/uplink
	sed -n -i "/^IFNAME=/!p; /^IFNAME=/h; \${g;p}" /run/uplink
) 9>>/run/uplink

. /etc/bratwurst
if [ "${PREFIX:-}" ]; then
	PREFIXES="$PREFIX,4294967295,4294967295" \
		/usr/share/dhcpc.script $IFNAME informed
)

sv up odhcp6c

exit 0
