#!/bin/sh

set -eu

panic () {
	echo init died, existing to shell
	exec /bin/sh
}
trap panic 0

run-parts /etc/rc.d

mkdir -p /var/spool/sv
find /etc/sv -type d -name supervise | xargs -r rm -rf
find /etc/sv -mindepth 1 -maxdepth 1 -type d \
	| sed 's~.*/\([^/]*\)~\1~; s~.*~/var/spool/sv/&\n/etc/sv/&/supervise~' \
	| xargs -r -n2 ln -f -s
find /etc/sv -mindepth 2 -maxdepth 2 -type d -name log \
	| sed 's~.*/\([^/]*\)/log~\1~; s~.*~/var/spool/sv/&.log\n/etc/sv/&/log/supervise~' \
	| xargs -r -n2 ln -f -s

mkdir /var/service
find /etc/sv -mindepth 1 -maxdepth 1 -type d \
	| sed 's~.*/\([^/]*\)~\1~; s~.*~/etc/sv/&\n/var/service/&~' \
	| xargs -r -n2 ln -f -s

exec runsvdir -s /sbin/siginit /var/service
