#!/bin/sh

set -eu

. /opt/bratwurst/config

if [ "$NETWORK" != "pppoe" ]; then
	sv once .
	exit 0
fi

TYPE=$(awk 'NR > 1 { print $2 }' /proc/net/atm/devices)

# wait for the ATM interface to become available
[ -n "$TYPE" ] || exit 1
# wait for carrier, do nothing (HACK: assume '0')
grep -q 1 /sys/class/atm/${TYPE}0/carrier || exit 1

case $ATM_ENCAP in
llc)		ENCAP=0;;
vcmux)		ENCAP=1;;
esac

exec /usr/sbin/br2684ctl -c $UPLINK_PORT -e $ENCAP -a $UPLINK_PORT.$ATM_VPI.$ATM_VCI
