#!/bin/sh

set -eu

mount					-t proc		proc	/proc
mount					-t sysfs	sysfs	/sys

mount -o remount,rw,nodev					/
mount -o nosuid,nodev,noexec,mode=1777	-t tmpfs	tmpfs	/tmp
mount -o nosuid,nodev,noexec		-t tmpfs	tmpfs	/run
mount -o nosuid,nodev			-t tmpfs	tmpfs	/var

mkdir -m 1777 /run/lock

exit 0
